/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PQCTAnalysisJNI */

#ifndef _Included_PQCTAnalysisJNI
#define _Included_PQCTAnalysisJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PQCTAnalysisJNI
 * Method:    execute
 * Signature: (Ljava/lang/String;SLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PQCTAnalysisJNI_execute
  (JNIEnv *, jobject, jstring, jshort, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
