/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PQCT_AnalysisJNI */

#ifndef _Included_PQCT_AnalysisJNI
#define _Included_PQCT_AnalysisJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PQCT_AnalysisJNI
 * Method:    Execute
 * Signature: (Ljava/lang/String;S)V
 */
JNIEXPORT void JNICALL Java_PQCT_1AnalysisJNI_Execute
  (JNIEnv *, jobject, jstring, jshort);

#ifdef __cplusplus
}
#endif
#endif
